import type { ServerSummary, TrackedPlayerPreview } from '@/lib/battlemetrics/types';

export const popularServers: ServerSummary[] = [
  {
    id: 'rustoria-eu-main',
    name: 'Rustoria EU Main',
    description: 'Servidor vanilla de alta poblacion, buen objetivo para grupos grandes.',
    ip: '148.251.96.131',
    port: 28015,
    players: 421,
    maxPlayers: 500,
    queue: 38,
    ping: 42,
    region: 'EU',
    country: 'DE',
    map: 'Procedural 4500',
    mapSize: 4500,
    seed: 829314,
    wipeSchedule: 'Jueves 20:00',
    wipeAgeHours: 19,
    status: 'online',
    connectedPlayers: [
      { id: 'pedro', name: 'Pedro', onlineMinutes: 182, lastSeen: 'Ahora', tags: ['Muy activo'] },
      { id: 'night-ak', name: 'NightAK', onlineMinutes: 51, lastSeen: 'Ahora', tags: ['AK'] },
      { id: 'soloq', name: 'SoloQ', onlineMinutes: 24, lastSeen: 'Ahora', tags: [] },
      { id: 'mara', name: 'Mara', onlineMinutes: 207, lastSeen: 'Ahora', tags: ['Posible aliado'] },
    ],
    markers: [
      { id: 'launch', label: 'Launch', note: 'Movimiento constante', x: 62, y: 34, tone: 'sky' },
      { id: 'h15', label: 'H15', note: 'Base grande', x: 30, y: 58, tone: 'rust' },
    ],
    activity: [
      { id: 'a1', time: '20:01', playerName: 'Pedro', type: 'connected' },
      { id: 'a2', time: '20:12', playerName: 'NightAK', type: 'connected' },
      { id: 'a3', time: '20:30', playerName: 'SoloQ', type: 'disconnected' },
    ],
  },
  {
    id: 'atlas-vanilla-es',
    name: 'Atlas Vanilla ES Trio',
    description: 'Servidor trio con ping bajo para Espana y cola manejable.',
    ip: '51.178.22.90',
    port: 28015,
    players: 176,
    maxPlayers: 250,
    queue: 4,
    ping: 29,
    region: 'EU',
    country: 'ES',
    map: 'Procedural 4000',
    mapSize: 4000,
    seed: 391022,
    wipeSchedule: 'Viernes 18:00',
    wipeAgeHours: 7,
    status: 'online',
    connectedPlayers: [
      { id: 'pedro', name: 'Pedro', onlineMinutes: 88, lastSeen: 'Ahora', tags: ['Vecino'] },
      {
        id: 'carlos',
        name: 'Carlos',
        onlineMinutes: 14,
        lastSeen: 'Ahora',
        tags: ['Clan enemigo'],
      },
      { id: 'mara', name: 'Mara', onlineMinutes: 130, lastSeen: 'Ahora', tags: ['Posible aliado'] },
      { id: 'raider', name: 'Raider_404', onlineMinutes: 67, lastSeen: 'Ahora', tags: [] },
      { id: 'sara', name: 'Sara', onlineMinutes: 42, lastSeen: 'Ahora', tags: [] },
    ],
    markers: [
      { id: 'h15', label: 'H15', note: 'Vecinos activos', x: 28, y: 42, tone: 'rust' },
      { id: 'base', label: 'Base', note: 'Posible duo', x: 72, y: 67, tone: 'green' },
      { id: 'metro', label: 'Metro', note: 'Ruta segura', x: 45, y: 72, tone: 'gold' },
    ],
    activity: [
      { id: 'b1', time: '19:48', playerName: 'Mara', type: 'connected' },
      { id: 'b2', time: '20:01', playerName: 'Pedro', type: 'connected' },
      { id: 'b3', time: '20:30', playerName: 'Carlos', type: 'connected' },
    ],
  },
  {
    id: 'moose-us-monthly',
    name: 'Rusty Moose US Monthly',
    description: 'Monthly competitivo con poblacion estable y ping alto desde Europa.',
    ip: '104.129.132.75',
    port: 28015,
    players: 289,
    maxPlayers: 350,
    queue: 12,
    ping: 118,
    region: 'NA',
    country: 'US',
    map: 'Procedural 4250',
    mapSize: 4250,
    seed: 770413,
    wipeSchedule: 'Primer jueves',
    wipeAgeHours: 44,
    status: 'online',
    connectedPlayers: [
      { id: 'moose-one', name: 'MooseOne', onlineMinutes: 95, lastSeen: 'Ahora', tags: [] },
      {
        id: 'builder',
        name: 'BuilderBob',
        onlineMinutes: 230,
        lastSeen: 'Ahora',
        tags: ['Muy activo'],
      },
      { id: 'terra', name: 'Terra', onlineMinutes: 36, lastSeen: 'Ahora', tags: [] },
    ],
    markers: [
      { id: 'oil', label: 'Oil', note: 'Peleas frecuentes', x: 76, y: 31, tone: 'sky' },
      { id: 'snow', label: 'Snow', note: 'Bases grandes', x: 39, y: 22, tone: 'rust' },
    ],
    activity: [
      { id: 'c1', time: '18:15', playerName: 'BuilderBob', type: 'connected' },
      { id: 'c2', time: '19:02', playerName: 'Terra', type: 'connected' },
      { id: 'c3', time: '19:44', playerName: 'MooseOne', type: 'disconnected' },
    ],
  },
];

export const trackedPlayers: TrackedPlayerPreview[] = [
  {
    id: 'pedro',
    name: 'Pedro',
    server: 'Atlas Vanilla ES Trio',
    tags: ['Vecino', 'Muy activo'],
    status: 'connected',
    lastSeen: 'Ahora',
  },
  {
    id: 'carlos',
    name: 'Carlos',
    server: 'Rustoria EU Main',
    tags: ['Clan enemigo', 'AK'],
    status: 'disconnected',
    lastSeen: '22:31',
  },
  {
    id: 'mara',
    name: 'Mara',
    server: 'Atlas Vanilla ES Trio',
    tags: ['Posible aliado'],
    status: 'connected',
    lastSeen: 'Ahora',
  },
];
